objects/Deferment__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Deferments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Deferments_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Deferments_Product_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deferment</label>
    <nameField>
        <displayFormat>DEF#{MM}{DD}{000}</displayFormat>
        <label>Deferment  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deferments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deferment_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deferment__c</fullName>
        <label>Deferment</label>
        <referenceTo>Deferment__c</referenceTo>
        <relationshipLabel>Deferment Approvals</relationshipLabel>
        <relationshipName>Deferment_Approvals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Partner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deferment Approval</label>
    <nameField>
        <displayFormat>DA#{000000}</displayFormat>
        <label>Approvals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deferment Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DefermentTrigger_Helper.cls
/* @Author      Mtha Gumede
* @Company:     Absa
* @Description: Helper class for Derferment trigger
* @Date:        10/2018
* @TestClasses:
* History
* <Date>      <Authors Name>    <Brief Description of Change>*/
public class DefermentTrigger_Helper {
    
    static public void CreateDefermentApprovals(list<Deferment__c> newDeferment) {
        
        list<Deferment_Approval__c>Defermentaproval = new list<Deferment_Approval__c>(); 
        list<RecordType>RecordTypes = new list<RecordType>();
        
        for(RecordType rt : [SELECT Id,DeveloperName FROM RecordType WHERE SobjectType = 'Deferment_Approval__c']){
            RecordTypes.add(rt);
        }
        
        
        for(Deferment__c deferment :newDeferment){
            for(RecordType rt :RecordTypes){
                
                Deferment_Approval__c defermentApproval = new Deferment_Approval__c();
                defermentApproval.Deferment__c = deferment.id;
                defermentApproval.RecordTypeId = rt.id;
                defermentApproval.Credit__c = deferment.Credit_Approver__c;                 
                defermentApproval.legal__c = deferment.Legal_Approver__c;
                defermentApproval.Product_Partner__c =deferment.Product_Approver__c;
                
                Defermentaproval.add(defermentApproval);
            }   
        }
        if (!Defermentaproval.isEmpty()){
            
            try{
                
                insert Defermentaproval;
                
            }
            catch (Exception e) {
                //Insert to a log object 
                system.debug('Defermentaproval not inserted');
                
            }
            
        }
    }
}